export const INITIAL_REQUEST_ACTION = "INITIAL_REQUEST";
export const REQUEST_NEWS_ACTION = "REQUEST_NEWS";
export const RECEIVE_NEWS_ACTION = "RECEIVE_NEWS";
export const RECEIVE_NEWS_FAILED_ACTION = "RECEIVE_NEWS_FAILED";
