# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp

  target 'NewsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NewsApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp-tvOS

  target 'NewsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
